version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
    ports:
      - 5433:5432

volumes:
  postgres:

networks:
  postgres:
    external: true
    name: postgres
